# Generated by Django 3.2 on 2022-07-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220706_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icons',
        ),
    ]
